services:
  scorpion_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scorpion_backend
    working_dir: /var/www
    ports:
      - "8080:8080"


  scorpion_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scorpion_frontend
    working_dir: /var/www
    ports:
      - "8081:5173"

